api/src/main/java/org/eclipse/microprofile/health/HealthStatus.java, api/src/main/java/org/eclipse/microprofile/health/HttpBinding.java
Isn't this frowned upon in most Java programming styles?
Keep it clean :)
=> Remove yoda conditions

api/pom.xml, pom.xml, tck/pom.xml
Signed-off-by: Jeff Mesnil <jmesnil@gmail.com>
=> clean up POM dependencies

tck/running_the_tck.asciidoc
Signed-off-by: Jeff Mesnil <jmesnil@gmail.com>
=> [TCK] add instructions to run the TCK

api/pom.xml, sample-implementation/.gitignore, sample-implementation/pom.xml, spec/.gitignore, spec/src/main/asciidoc/protocol-wireformat.adoc, tck/.gitignore, tck/pom.xml
Task-Url: https://github.com/eclipse/microprofile-health/issues/18
Signed-off-by: Werner Keil <werner.keil@gmx.net>
=> 18: Fix API groupId

README.adoc
Brings the readme en par with the changes by @starksm64
=> Update the readme to reflect the new API terms introduced by PR #60

spec/pom.xml, spec/src/main/asciidoc/microprofile-health-spec.asciidoc, spec/src/main/asciidoc/protocol-wireformat.adoc, tck/src/main/java/org/eclipse/microprofile/health/tck/NoProcedureSuccessfulTest.java
Signed-off-by: Scott Stark <starksm64@gmail.com>
=> Issue #3, do not use 204 when no procedures are installed

tck/src/main/java/org/eclipse/microprofile/health/tck/EnforceQualifierTest.java
@johnament This should fix the assertion we talked about in #71
=> Fix EnforceQualifierTest to reflect changes in #3

pom.xml, tck/pom.xml
Reverts eclipse/microprofile-health#77
=> Revert "Cleaning up the pom file to remove unneeded dependencies.  This close…"

api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
Added a further method to access the builder without supplying a name param
=> Added builder() access method to HealthCheckResponse

api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
Prospective fix for #103 
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
=> Fix self-assignment bug in setResponseProvider method

README.adoc
Update response json example as per newest Protocol and Wireformat specification.
=> Update response json example

README.adoc
You said "keep the PRs coming" ;)
=> Add full stop

pom.xml, spec/src/main/asciidoc/overview.adoc
=> microprofile-health-107 Reintroduce original author names

spec/src/main/asciidoc/overview.adoc
Signed-off-by: Doychin Bondzhev <doychin@dsoft-bg.com>
=> Fix for issue 131.

spec/src/main/asciidoc/protocol-wireformat.adoc
this PR makes the changes proposed in #140
=> specify handling of failures when invoking health checks

spec/src/main/asciidoc/protocol-wireformat.adoc
This PR makes the changes proposed in #138 
(NOTE: I signed en ECA after submitting this PR)
=> clarify difference between having no checks at all vs. no checks available

spec/src/main/asciidoc/java-api.adoc
=> Health checks are unordered

spec/src/main/asciidoc/java-api.adoc, spec/src/main/asciidoc/overview.adoc, spec/src/main/asciidoc/protocol-wireformat.adoc
A few small text adjustments found when going through the specification text. 
=> Fix spec text inconsistencies

spec/src/main/asciidoc/java-api.adoc
=> Add example where Health procedures are produced instead of defined by bean class

api/pom.xml, pom.xml, sample-implementation/pom.xml, spec/pom.xml, tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/health/tck/EnforceQualifierTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithAttributes.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithoutQualifier.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegateCheck.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedCheck.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulCheck.java
Issue #119 was assuming that `@Health` would become optional
=> Microprofile health 163 switch to 2.0 and revert #119

tck/src/main/java/org/eclipse/microprofile/health/tck/DelegateHealthSuccessfulTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/EnforceQualifierTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/HealthCheckResponseAttributesTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleLivenessFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleReadinessFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/NoProcedureSuccessfulTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/OnlySuccessfulProcedureTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SimpleHttp.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SingleHealthFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SingleHealthSuccessfulTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegateHealth.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedHealth.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedLiveness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedReadiness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/HealthWithAttributes.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulHealth.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulLiveness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulReadiness.java
For the sake of efficiency I propose that review should only be done on actual code errors or typos.
Please, keep the possible missing test for after RC1 release
=> Add TCK tests for Liveness and Readiness

pom.xml
There was duplicated entries in the pom.xml
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>
=> Removed duplicate entries in pom file. Up the rat version

spec/src/main/asciidoc/java-api.adoc, spec/src/main/asciidoc/protocol-wireformat.adoc
fixes #160
Correct Asciiddoc formating error
=> microprofile-health-160 MP-HC 1.0 response schema does not validate

api/pom.xml, api/src/main/java/org/eclipse/microprofile/health/package-info.java
Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>
=> #162 plugin baseline and properly maintain api version

api/pom.xml, pom.xml, spec/pom.xml, spec/src/main/asciidoc/microprofile-health-spec.adoc, tck/pom.xml
Extract version as mvn properties 
Update some dependencies
Correct version of Asciidoc generated docs
=> Maven and asciidoctor cleaning

spec/src/main/asciidoc/microprofile-health-spec.adoc, spec/src/main/asciidoc/overview.adoc, spec/src/main/asciidoc/release_notes.asciidoc
=> Adding release notes

tck/running_the_tck.asciidoc
Signed-off-by: svenhaag <sven-haag@gmx.de>
=> Updated dependency versions

api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java, api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponseBuilder.java
=> Fix javadoc and checkstyle errors in build

tck/running_the_tck.asciidoc
Signed-off-by: Felix Wong <fmhwong@ca.ibm.com>
Fixes #185
=> Use extension instead of another ResourceProvider

README.adoc
=> Added code syntax highlighting to README

spec/src/main/asciidoc/java-api.adoc, tck/src/main/java/org/eclipse/microprofile/health/tck/CDIProducedProceduresTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CDIProducedProcedureCheck.java
Signed-off-by: pgunapal pgunapal@ca.ibm.com
=> Added CDI Produced Procedures TCK and fixed java-api document

pom.xml, tck/pom.xml, tck/src/main/java/org/eclipse/microprofile/health/tck/JsonSchemaValidationTest.java, tck/src/main/resources/health-check-schema.json
=> Add TCK for JSON schema validation

pom.xml, tck/pom.xml
=> issue87 Remove unnecessary duplicate arquillian import

api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CDIProducedProcedureCheck.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithoutQualifier.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelayedCheck.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedHealth.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedLiveness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedReadiness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulHealth.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulLiveness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulReadiness.java
=> issue184 Add convenience methods for creating health check responses

api/src/main/java/org/eclipse/microprofile/health/Health.java, api/src/main/java/org/eclipse/microprofile/health/HealthCheck.java, api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java, api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponseBuilder.java, api/src/main/java/org/eclipse/microprofile/health/spi/HealthCheckResponseProvider.java
from a bigger part covered in #183 (thanks @sdaschner)
resolves #178
=> issue178 Add JavaDoc improvements

spec/src/main/asciidoc/protocol-wireformat.adoc, tck/running_the_tck.asciidoc
=> issue180 Add a config property for disabling default vendor procedures

README.adoc
=> Updated README.adoc with convenient method approach

api/pom.xml, pom.xml, tck/pom.xml
=> issue-214: Update to Jakarta EE8 APIs

api/pom.xml, api/src/main/java/org/eclipse/microprofile/health/HealthGroup.java, api/src/main/java/org/eclipse/microprofile/health/Liveness.java, api/src/main/java/org/eclipse/microprofile/health/Readiness.java
=> microprofile-health-224 Add annotation literals for all Qualifier in the spec

pom.xml
=> microprofile-health-230 Jenkins build failed with signature failure

api/pom.xml, api/src/main/java/org/eclipse/microprofile/health/package-info.java
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
=> #228 update package version based on functional changes

pom.xml, tck/pom.xml
Fixes #239
Also switch to CDI api to version 2.0
=> microprofile-health-239 Remove Guava exclusion for TCK

spec/src/main/asciidoc/release_notes.asciidoc
=> Add release notes

README.adoc
Since MP 3.3, HealthCheckResponse is concrete
=> HealthCheckResponse is a concrete class

api/pom.xml, pom.xml, spec/pom.xml, tck/pom.xml
=> Prepare for 3.0 development

README.adoc
Issue #222
Signed-off-by: Ralph Soika <ralph.soika@imixs.com>
=> changed layout of inline code

api/pom.xml, pom.xml, tck/pom.xml
=> Issue220 Mark spec dependencies as "provided"

.editorconfig
=> Add .editorconfig from MP config

spec/src/main/asciidoc/protocol-wireformat.adoc, spec/src/main/asciidoc/release_notes.asciidoc
Also fixed small asciidoc issue
=> Release notes for 3.0

spec/src/main/asciidoc/release_notes.asciidoc
=> Update the release notes to spell out the incompatible changes

api/pom.xml
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
=> Update the baseline to the latest released version

pom.xml, tck/src/main/resources/health-check-schema.json
Oversight included with WG changes.
=> Fix rat plugin configuration for json files

.github/ISSUE_TEMPLATE/01-compatible-certification-request.md
... so it can be displayed in the menu.
=> Fix the certification issue template name

README.adoc, api/src/main/java/org/eclipse/microprofile/health/Startness.java, spec/src/main/asciidoc/java-api.adoc, spec/src/main/asciidoc/overview.adoc, spec/src/main/asciidoc/protocol-wireformat.adoc, tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleStartnessFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SingleStartnessFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SingleStartnessSuccessfulTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/TCKBase.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedStartness.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulStartness.java
=> Add Startness probes

api/src/main/java/org/eclipse/microprofile/health/Startness.java, api/src/main/java/org/eclipse/microprofile/health/package-info.java, tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleStartnessFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SingleStartnessFailedTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/SingleStartnessSuccessfulTest.java, tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulStartness.java
Also apply formating for the new startness feature that was merged before the parent pom with the formatter plugin was integrated.
=> Update OSGi version to 2.1

api/src/main/java/org/eclipse/microprofile/health/Liveness.java, api/src/main/java/org/eclipse/microprofile/health/Readiness.java, api/src/main/java/org/eclipse/microprofile/health/Startness.java
=> Updated all Health check qualifiers to have consistent annotations

.github/ISSUE_TEMPLATE/02-use-case.md, .github/ISSUE_TEMPLATE/03-clarification.md, .github/ISSUE_TEMPLATE/04-bug-report.md, .github/ISSUE_TEMPLATE/05-impl-proposal.md, .github/ISSUE_TEMPLATE/06-process-change.md
Copied from MP Config. I believe this can be really useful.
=> Add issue templates

spec/pom.xml
=> Remove specs package from spec module groupId

pom.xml, spec/src/main/asciidoc/license-alv2.asciidoc, spec/src/main/asciidoc/license-efsl.asciidoc
=> Update licenses years to be set by properties

README.adoc
=> Updated CDI Integration section to add Startup in README
