- api/NOTICE
- pom.xml
- ri/NOTICE
- ri/pom.xml
- tck/pom.xml
Reverted Heiko's recent merge ( #6 ) since that version of swarm does not seem to exist in maven...  And, in order for my changes to build correctly, I had to revert to a working version of swarm -- 2017.4.0.  Heiko can redo his changes once a proper version of swarm is detected and tested.
This is in support of Issue #5.
> update to dependency version and a couple of new NOTICE files

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/health/HealthCheckProcedure.java
- api/src/main/java/org/eclipse/microprofile/health/HttpBinding.java
- pom.xml
- ri/README.adoc
- ri/pom.xml
- tck/src/main/java/org/eclipse/microprofile/health/tck/HealthPayloadTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CDIHealthCheck.java
```
package org.eclipse.microprofile.health.tck.deployment;
[...]
public class CDIHealthCheck implements HealthCheckProcedure {
@Override
public HealthStatus execute() {
return HealthStatus.named("CDI").up();
}
}
```
> First attempt on CDI managed health procedures

- api/src/main/java/org/eclipse/microprofile/health/HealthStatus.java
Minor edit - no functionality changes.
Removing this variable because it's used so inconsistently (line 110 - used at start and then not again on this line in places it should).
Plus, the variable name is longer than what it actually represents, and since it's unlikely to ever change, doesn't even work as a shortcut.
> Remove ESCAPED_QUOTE variable

- tck/running_the_tck.asciidoc
- tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleProceduresFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/ResponseAttributesTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/TCKConfiguration.java
Implementations that runs the TCK can configure the HTTP health URL with
the System property org.eclipse.microprofile.health.tck.url (default is
http://localhost:8080/health).
> [TCK] Health URL is configurable

- tck/src/main/java/org/eclipse/microprofile/health/tck/DelegateProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegateCheck.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegationTarget.java
We probably need more extensive tests to verify all sorts of CDI discovery and injection scenarios, but this test at least  verifies that beans that are discovered as `HealthChecks` are actually managed beans (i.e. `@Inject`) works on them. 
This is a sanity test and more needs to follow, but as a baseline this should work for 1.0 I think
> Added a test to verify delegation across injection targets works

- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponseBuilder.java
- spec/src/main/asciidoc/protocol-wireformat.adoc
- tck/src/main/java/org/eclipse/microprofile/health/tck/DelegateProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/HealthCheckResponseAttributesTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleProceduresFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithAttributes.java
In the wireformat the following attribute names have been changed:
- ‘id’ -> ’name’
- ‘result’ -> ‘state’
In the Java API the following method signature has been changed to match the JSON terms:
- getAttributes() / withAttributes() -> getData() / withData()
> Fix #40: Align protocol and API terms

- README.adoc
- api/src/main/java/org/eclipse/microprofile/health/Health.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/EnforceQualifierTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithoutQualifier.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegateCheck.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedCheck.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulCheck.java
This commit also includes a test to verify that only procedures with `@Health` will be discovered (enforcement)
> Fix #53: Added @Health annotation to TCK deployments

- api/pom.xml
- api/src/main/java/org/eclipse/microprofile/health/Health.java
- pom.xml
This is to resolve an issue introduced with #53, it was decided ot use @Health to demarcate classes that should be health checks.  However, for that to work we need the qualifier to actually be a qualifier.
> Introduce @Health as an actual qualifier

- README.adoc
- spec/src/main/asciidoc/java-api.adoc
Presumably these were missed during the refactor of `getAttributes()` to `getData()`.
Also fixes a couple of typos:
* Removes the redundant word _other_ from line 24
* Made _health checks_ singular on line 34, as it probably shouldn't be plural
* Adds in a comma on line 26  for readability
> Fix Misnamed Methods in README and Java-API Doc

- spec/src/main/asciidoc/java-api.adoc
As stated in #111 the JavaApi example in the spec does not compile.
> Add a .build() for the response to be built. 

- api/src/main/java/org/eclipse/microprofile/health/Health.java
- spec/src/main/asciidoc/java-api.adoc
- tck/src/main/java/org/eclipse/microprofile/health/tck/WithQualifierTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithAttributes.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/CheckWithHealthQualifier.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegateCheck.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedCheck.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulCheck.java
Solving #119:
2 CDI beans with type HealthCheck type and Default or Health qualifier exist
> microprofile-health-119 Clarify integration with CDI

- README.adoc
- sample-implementation/README.adoc
- spec/src/main/asciidoc/java-api.adoc
- spec/src/main/asciidoc/protocol-wireformat.adoc
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/health/tck/DelegateProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/HealthCheckResponseAttributesTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleProceduresFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/NoProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureSuccessfulTest.java
Related to #125 
This PR:
* replaces (global) `outcome` with `status` as discussed in #125 
* replaces (check) `state` with `status` as discussed in #125 
* remove the reference to the `@Health` annotation from the main README file
* includes some cleanup in the README files and pom.xml file
> Rename outcome to status

- tck/src/main/java/org/eclipse/microprofile/health/tck/DelegateProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/HealthCheckResponseAttributesTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleProceduresFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/NoProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/WithQualifierTest.java
Setting testable to false for deployments in TCK, all the tests are `@RunAsClient`
Details about test run modes in https://docs.jboss.org/author/display/ARQ/Test+run+modes
Execution of current TCK causes warnings on server side
```
Failed to define class org.eclipse.microprofile.health.tck.SingleProcedureSuccessfulTest in Module "deployment.tck.war" from Service Module Loader:
java.lang.NoClassDefFoundError: Failed to link org/eclipse/microprofile/health/tck/SingleProcedureSuccessfulTest
(Module "deployment.tck.war" from Service Module Loader): org/eclipse/microprofile/health/tck/SimpleHttp
```
> Setting testable to false for deployments in TCK

- api/pom.xml
Presumably the bundle shouldn't be identifying itself as fault tolerance?
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
> Correct Bundle Name

- api/src/main/java/org/eclipse/microprofile/health/Liveness.java
- api/src/main/java/org/eclipse/microprofile/health/Readiness.java
- api/src/main/java/org/eclipse/microprofile/health/spi/package-info.java
- spec/src/main/asciidoc/java-api.adoc
- spec/src/main/asciidoc/overview.adoc
- spec/src/main/asciidoc/protocol-wireformat.adoc
First version of the pull request for #35.
`HealthCheckResponse` description will probably need to be change to take Readiness into account.
> microprofile-health-35 Provide different types of health check

- tck/src/main/java/org/eclipse/microprofile/health/tck/DelegateProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/EnforceQualifierTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/HealthCheckResponseAttributesTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleProceduresFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/NoProcedureSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleProcedureSuccessfulTest.java
This reverts commit 45e96cd8856ba74d244ba13104ffe5350a900a59.
testable = false in deployments prohibits any addition of resources (classes, service loader) to the deployment that is created by the TCK which is something implementations typically probably need to do.
Signed-off-by: xstefank xstefank122@gmail.com
> Revert "Setting testable to false for deployments in TCK"

- pom.xml
- tck/pom.xml
- tck/src/main/java/org/eclipse/microprofile/health/tck/JsonSchemaValidationTest.java
- tck/src/main/resources/health-check-schema.json
This PR is adding new dependency - json-schema-validator.
Unfortunately, it seems that JSON-P/B don't support schema validation and I am unable to find where to file feature requests for these specs. In every case it will take some time and that's why I've decided for third party dependency.
> Add TCK for JSON schema validation

- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponseBuilder.java
- spec/src/main/asciidoc/java-api.adoc
Added some JavaDoc and a note to the spec document.
Especially the need for a named health check response made me run into errors when using `HealthCheckResponse#builder()` without setting a name.
> Added JavaDoc for clarification

- tck/src/main/java/org/eclipse/microprofile/health/tck/DelayedCheckTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelayedCheck.java
This TCK tests validates that if health check creation (here Readiness check) takes some time, the requests that are received before the health check instance is created report the right answer -- essentially meaning that all health checks must be invoked when request comes.
> Add DelayedCheckTest TCK

- pom.xml
fixes #195
For the record, CDI is only used in TCK. API only used AtInject specification
> microprofile-health-195 Exclude EL API transitive dependency

- api/pom.xml
- pom.xml
- tck/pom.xml
This reverts commit 3e4f5002b3ef402bd83c8c1076cbe7be9de713a9, reversing
changes made to 72b807cddd22ff9ae6eeb9580c45e73762dec617.
As decided on the [MP hangout](https://docs.google.com/document/d/16v3jVkcDzVz9BVU5aGEzPVbK-a8BIx7S1gbqToVUaLs/edit#bookmark=id.go4e619czr4s) we are staying on Java EE 8 for 3.3 thus reverting the upgrade to Jakarta EE 8.
> Revert "Merge pull request #217 from xstefank/issue-214"

- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
- spec/src/main/asciidoc/java-api.adoc
fixes #194
Make HealthCheckResponse a concrete class and add constructors for backward compatibility and usage on the consuming end from MP RestClient
> microprofile-health-194 Better integration with JSON-B and MP Rest Cient

- api/src/main/java/org/eclipse/microprofile/health/HealthGroup.java
- api/src/main/java/org/eclipse/microprofile/health/HealthGroups.java
- spec/src/main/asciidoc/java-api.adoc
- spec/src/main/asciidoc/protocol-wireformat.adoc
- tck/src/main/java/org/eclipse/microprofile/health/tck/MultipleCustomFailedTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/SingleCustomSuccessfulTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/TCKBase.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/FailedCustom.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/SuccessfulCustom.java
fixes #81 
Adding annotations
Amend specification
Add TCK tests
> microprofile-health-81 Ability to execute only some health checks

- README.adoc
- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponseBuilder.java
- api/src/main/java/org/eclipse/microprofile/health/package-info.java
- spec/src/main/asciidoc/java-api.adoc
- spec/src/main/asciidoc/protocol-wireformat.adoc
- tck/src/main/java/org/eclipse/microprofile/health/tck/HealthCheckResponseValidationTest.java
- tck/src/main/java/org/eclipse/microprofile/health/tck/deployment/DelegateHealth.java
> Issue-243 Updated HealthCheckResponse state property to status

- spec/src/main/asciidoc/microprofile-health-spec.adoc
- spec/src/main/asciidoc/overview.adoc
- spec/src/main/asciidoc/release_notes.asciidoc
Signed-off-by: Scott Kurz <skurz@us.ibm.com>
Went looking for whether the official name was "MP Health" vs. "MP Health Check".
I found this discussion: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/microprofile/eyz7MSIFUVg/-siZRL6pAgAJ
So I submitted this PR.   I won't feel bad if it turns out you already discussed this... seemed easier to just send a PR than start another discussion.
> Cleanup incorrect? "MicroProfile Health Check" spec names in spec/doc.

- spec/src/main/asciidoc/protocol-wireformat.asciidoc
> Clarified the default readiness empty response statement

- tck/pom.xml
Need to update the `org.glassfish.jakarta.json` version to 2.0.0 in the TCK dependency, to align with Jakarta EE 9.1, in order for the TCKs to run properly with the jakarta.json APIs.
> Updated the org.glassfish.jakarta.json version in TCK to align with Jakarta EE 9.1

- api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponse.java
- api/src/main/java/org/eclipse/microprofile/health/package-info.java
- spec/src/main/asciidoc/release_notes.asciidoc
Quick attempt at refactoring `HealthCheckResponse` to use just `Map<>` as the data type for the `data` field.
This is a breaking change, since the ctor is affected, hence the `microprofile-health-api` version is bumped as well.
~**Draft**, since the changes require #331 (rebased on it temporarily)~
Fixes #323
FYI @xstefank
> Refactoring HealthCheckResponse to remove Optional from the data field
